(() => {
  const menuButton = document.querySelector('#menuButton'); const nav = document.querySelector('#mainNav');
  const themeToggle = document.querySelector('#themeToggle') || (() => { if (!menuButton) return null; const button = document.createElement('button'); button.id = 'themeToggle'; button.type = 'button'; button.className = 'rounded-lg border border-slate-200 px-3 py-2 text-sm font-bold'; button.setAttribute('aria-label', 'Ubah tema'); menuButton.parentElement.insertBefore(button, menuButton); return button; })();
  const applyTheme = dark => { document.documentElement.classList.toggle('dark-mode', dark); if (themeToggle) { themeToggle.setAttribute('aria-pressed', String(dark)); themeToggle.textContent = dark ? '☀ Terang' : '☾ Gelap'; } };
  applyTheme(localStorage.getItem('nihongo-theme') === 'dark');
  themeToggle?.addEventListener('click', () => { const dark = !document.documentElement.classList.contains('dark-mode'); applyTheme(dark); localStorage.setItem('nihongo-theme', dark ? 'dark' : 'light'); });
  if (menuButton) menuButton.addEventListener('click', () => { const closed = nav.classList.toggle('hidden'); menuButton.setAttribute('aria-expanded', String(!closed)); });
  document.querySelectorAll('.nav-link').forEach(link => link.addEventListener('click', () => { nav?.classList.add('hidden'); menuButton?.setAttribute('aria-expanded','false'); }));
  const toggle = document.querySelector('#furiganaToggle');
  if (toggle) toggle.addEventListener('click', () => { const off = document.body.classList.toggle('furigana-off'); toggle.setAttribute('aria-checked', String(!off)); document.querySelector('#furiganaState').textContent = off ? 'OFF' : 'ON'; document.querySelector('#furiganaDot').classList.toggle('bg-crimson', !off); document.querySelector('#furiganaDot').classList.toggle('bg-slate-400', off); });
  const entries = [
    { keys:'wa desu は です', title:'~ wa ~ desu', meaning:'Menyatakan identitas atau keadaan dengan sopan.', formula:'A は B です', example:'<ruby>私<rt>わたし</rt></ruby>は<ruby>高校生<rt>こうこうせい</rt></ruby>です。', translation:'Saya siswa SMA.' },
    { keys:'ni ikimasu pergi tujuan に いきます', title:'~ ni ikimasu', meaning:'Menyatakan pergi ke suatu tempat.', formula:'Tempat に 行きます', example:'<ruby>学校<rt>がっこう</rt></ruby>に<ruby>行<rt>い</rt></ruby>きます。', translation:'Saya pergi ke sekolah.' },
    { keys:'masen tidak negasi ません', title:'~ masen', meaning:'Menyatakan kegiatan yang tidak dilakukan.', formula:'Kata kerja masu → masen', example:'<ruby>明日<rt>あした</rt></ruby>は<ruby>勉強<rt>べんきょう</rt></ruby>しません。', translation:'Besok saya tidak belajar.' },
    { keys:'o kudasai minta をください', title:'~ o kudasai', meaning:'Meminta benda dengan sopan.', formula:'Benda を ください', example:'<ruby>先生<rt>せんせい</rt></ruby>、<ruby>本<rt>ほん</rt></ruby>をください。', translation:'Sensei, tolong berikan buku.' },
    { keys:'de belajar tempat perpustakaan で べんきょう', title:'~ de', meaning:'Menunjukkan tempat berlangsungnya kegiatan.', formula:'Tempat で Kata kerja', example:'<ruby>図書館<rt>としょかん</rt></ruby>で<ruby>勉強<rt>べんきょう</rt></ruby>します。', translation:'Saya belajar di perpustakaan.' },
    { keys:'to dengan dan と ともだち', title:'~ to', meaning:'Menghubungkan dua benda atau menyatakan bersama seseorang.', formula:'A と B / Orang と', example:'<ruby>友達<rt>ともだち</rt></ruby>と<ruby>話<rt>はな</rt></ruby>します。', translation:'Saya berbicara dengan teman.' },
    { keys:'ga ada aru imasu があります います', title:'~ ga arimasu / imasu', meaning:'Menyatakan keberadaan benda atau makhluk hidup.', formula:'Tempat に Benda が あります', example:'<ruby>教室<rt>きょうしつ</rt></ruby>に<ruby>机<rt>つくえ</rt></ruby>があります。', translation:'Ada meja di kelas.' },
    { keys:'tai ingin たいです', title:'~ tai desu', meaning:'Menyatakan keinginan melakukan sesuatu.', formula:'Bentuk masu tanpa masu + たいです', example:'<ruby>日本語<rt>にほんご</rt></ruby>を<ruby>話<rt>はな</rt></ruby>したいです。', translation:'Saya ingin berbicara bahasa Jepang.' },
    { keys:'kara made dari sampai から まで', title:'~ kara ~ made', meaning:'Menunjukkan batas awal dan akhir waktu atau tempat.', formula:'Waktu から Waktu まで', example:'<ruby>九時<rt>くじ</rt></ruby>から<ruby>三時<rt>さんじ</rt></ruby>まで<ruby>学校<rt>がっこう</rt></ruby>です。', translation:'Saya berada di sekolah dari jam sembilan sampai jam tiga.' },
    { keys:'aisatsu salam ohayou selamat pagi おはよう', title:'Aisatsu: Ohayou gozaimasu', meaning:'Salam yang digunakan pada pagi hari dengan sopan.', formula:'おはようございます', example:'おはようございます。', translation:'Selamat pagi.' },
    { keys:'aisatsu salam konnichiwa selamat siang halo こんにちは', title:'Aisatsu: Konnichiwa', meaning:'Salam yang umum digunakan pada siang hari.', formula:'こんにちは', example:'こんにちは。<ruby>元気<rt>げんき</rt></ruby>ですか。', translation:'Halo. Apa kabar?' },
    { keys:'aisatsu salam konbanwa selamat malam こんばんは', title:'Aisatsu: Konbanwa', meaning:'Salam yang digunakan pada malam hari.', formula:'こんばんは', example:'こんばんは。', translation:'Selamat malam.' },
    { keys:'aisatsu salam arigatou terima kasih ありがとう', title:'Aisatsu: Arigatou gozaimasu', meaning:'Ungkapan terima kasih dengan sopan.', formula:'ありがとうございます', example:'ありがとうございます。', translation:'Terima kasih.' },
    { keys:'aisatsu salam sumimasen maaf permisi すみません', title:'Aisatsu: Sumimasen', meaning:'Ungkapan untuk meminta maaf atau menarik perhatian seseorang.', formula:'すみません', example:'すみません、<ruby>駅<rt>えき</rt></ruby>はどこですか。', translation:'Permisi, stasiun ada di mana?' },
    { keys:'aisatsu salam sayounara sampai jumpa さようなら', title:'Aisatsu: Sayounara', meaning:'Salam perpisahan saat tidak akan bertemu dalam waktu dekat.', formula:'さようなら', example:'さようなら。また<ruby>明日<rt>あした</rt></ruby>。', translation:'Sampai jumpa. Sampai besok.' }
  ];
  const search = document.querySelector('#grammarSearch'); const results = document.querySelector('#grammarResults');
  if (search && results) { const render = () => { const query = search.value.toLowerCase().trim(); const found = entries.filter(entry => !query || `${entry.keys} ${entry.title} ${entry.meaning}`.toLowerCase().includes(query)); results.innerHTML = found.length ? found.map(entry => `<article class="rounded-xl border border-slate-200 bg-white p-4"><div class="flex flex-wrap justify-between gap-2"><strong class="text-crimson">${entry.title}</strong><span class="rounded-full bg-sakura/40 px-3 py-1 text-xs font-bold">${entry.formula}</span></div><p class="mt-2 text-sm text-slate-600">${entry.meaning}</p><p class="mt-3 font-display text-xl">${entry.example}</p><p class="mt-1 text-xs text-slate-500">${entry.translation}</p></article>`).join('') : '<p class="rounded-xl bg-white p-4 text-sm text-slate-500">Pola belum ditemukan.</p>'; }; search.addEventListener('input', render); render(); }
})();
